version: '3.8'

services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: ${DB_USER:-prompty}      
      POSTGRES_PASSWORD: ${DB_PASSWORD:-1234} 
      POSTGRES_DB: ${DB_NAME:-prompty}       
    ports:
      - "${DB_PORT:-5432}:5432"            
    volumes:
      - postgres-data:/var/lib/postgresql/data  

volumes:
  postgres-data: