-- insert role in to role_frameworks like (id, name) id is auto increment
-- role is mean occupation of user like engineer, doctor, lawyer, scientist, etc
INSERT INTO roles (name) VALUES 
    ('Engineer'),
    ('Doctor'),
    ('Lawyer'),
    ('Scientist'),
    ('Teacher'),
    ('Student'),
    ('Businessman'),
    ('Politician'),
    ('Farmer'),
    ('Artist'),
    ('Musician'),
    ('Actor'),
    ('Athlete'),
    ('Soldier'),
    ('Police'),
    ('Firefighter'),
    ('Chef'),
    ('Journalist'),
    ('Writer'),
    ('Photographer'),
    ('Designer'),
    ('Architect'),
    ('Dancer'),
    ('Singer'),
    ('Model'),
    ('Director'),
    ('Producer'),
    ('Cameraman'),
    ('Editor'),
    ('Cinematographer'),
    ('Sound Engineer'),
    ('VFX Artist'),
    ('Animator'),
    ('Game Developer'),
    ('Web Developer'),
    ('App Developer'),
    ('Software Developer'),
    ('Hardware Engineer'),
    ('Network Engineer'),
    ('Database Administrator'),
    ('System Administrator'),
    ('Cyber Security Expert'),
    ('Data Scientist'),
    ('Machine Learning Engineer'),
    ('Artificial Intelligence Expert'),
    ('Robotics Engineer'),
    ('Automation Engineer'),
    ('Electrical Engineer'),
    ('Mechanical Engineer'),
    ('Civil Engineer'),
    ('Chemical Engineer'),
    ('Aerospace Engineer'),
    ('Automobile Engineer'),
    ('Marine Engineer'),
    ('Mining Engineer'),
    ('Petroleum Engineer'),
    ('Environmental Engineer'),
    ('Biomedical Engineer'),
    ('Biotechnologist'),
    ('Geneticist'),
    ('Microbiologist'),
    ('Biochemist'),
    ('Pharmacist'),
    ('Physiotherapist'),
    ('Nurse'),
    ('Dentist'),
    ('Veterinarian'),
    ('Psychologist'),
    ('Psychiatrist'),
    ('Counselor'),
    ('Social Worker'),
    ('Human Resource Manager'),
    ('Marketing Manager'),
    ('Sales Manager'),
    ('Finance Manager'),
    ('Accountant'),
    ('Auditor'),
    ('Tax Consultant'),
    ('Investment Banker'),
    ('Stock Broker'),
    ('Insurance Agent'),
    ('Real Estate Agent'),
    ('Travel Agent'),
    ('Event Manager'),
    ('Tour Guide'),
    ('Hotel Manager'),
    ('Restaurant Manager'),
    ('Chef'),
    ('Baker'),
    ('Barista'),
    ('Bartender'),
    ('Waiter'),
    ('Housekeeper'),
    ('Security Guard'),
    ('Cleaner'),
    ('Gardener'),
    ('Driver'),
    ('Mechanic'),
    ('Plumber'),
    ('Electrician'),
    ('Carpenter'),
    ('Mason'),
    ('Welder'),
    ('Blacksmith'),
    ('Tailor'),
    ('Shoemaker'),
    ('Jeweler'),
    ('Watchmaker'),
    ('Painter'),
    ('Sculptor'),
    ('Potter'),
    ('Weaver'),
    ('Basket Weaver'),
    ('Basketball Player'),
    ('Football Player'),
    ('Cricket Player'),
    ('Tennis Player'),
    ('Golf Player'),
    ('Swimmer'),
    ('Runner'),
    ('Cyclist'),
    ('Boxer'),
    ('Wrestler'),
    ('Weightlifter'),
    ('Gymnast'),
    ('Yoga Instructor'),
    ('Martial Artist'),
    ('Coach'),
    ('Referee'),
    ('Umpire'),
    ('Sports Journalist'),
    ('Sports Commentator'),
    ('Sports Analyst'),
    ('Sports Broadcaster'),
    ('Sports Photographer'),
    ('Sports Videographer'),
    ('Sports Editor'),
    ('Sports Producer'),
    ('Sports Director'),
    ('Sports Cameraman'),
    ('Sports Sound Engineer'),
    ('Sports VFX Artist'),
    ('Sports Animator'),
    ('Sports Game Developer'),
    ('Sports Web Developer'),
    ('Sports App Developer'),
    ('Sports Software Developer'),
    ('Sports Hardware Engineer'),
    ('Sports Network Engineer'),
    ('Sports Database Administrator'),
    ('Sports System Administrator'),
    ('Sports Cyber Security Expert'),
    ('Sports Data Scientist'),
    ('Sports Machine Learning Engineer'),
    ('Sports Artificial Intelligence Expert'),
    ('Sports Robotics Engineer'),
    ('Sports Automation Engineer'),
    ('Sports Electrical Engineer'),
    ('Sports Mechanical Engineer'),
    ('Sports Civil Engineer'),
    ('Sports Chemical Engineer'),
    ('Sports Aerospace Engineer'),
    ('Sports Automobile Engineer'),
    ('Sports Marine Engineer'),
    ('Sports Mining Engineer'),
    ('Sports Petroleum Engineer'),
    ('Sports Environmental Engineer'),
    ('Sports Biomedical Engineer'),
    ('Sports Biotechnologist'),
    ('Sports Geneticist'),
    ('Sports Microbiologist'),
    ('Sports Biochemist'),
    ('Sports Pharmacist'),
    ('Sports Physiotherapist'),
    ('Sports Nurse'),
    ('Sports Dentist'),
    ('Sports Veterinarian'),
    ('Sports Psychologist'),
    ('Sports Psychiatrist'),
    ('Sports Counselor'),
    ('Sports Social Worker'),
    ('Sports Human Resource Manager');

