services:
  app:
    container_name: app
    build: ../.
    ports: 
      - "8080:8080"
    env_file:
      - .env
  pgsql:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=promptlab
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./initial_db:/docker-entrypoint-initdb.d/
volumes:
 postgres:
  driver: local
